name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: npm i - firebase
      run: |
        cd firebase
        npm i
        cd ..
    - name: npm i - vue
      run: |
        cd vue
        npm i
        cd ..
    - name: Build & Firebase Deploy
      run: |
        sudo npm install -g firebase-tools
        npm run pipeline-deploy
