name: Win History

on:
  push:
    branches: [ master, screenshot-action ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: screenshot leaderboard
      uses: ./actions/history-screenshots/
      with:
        api-key: ${{ secrets.FIREBASE_FUNCTION_KEY }}
    - name: Commit file to repo
      continue-on-error: true
      run: |
        git status
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "GitHub Action, history at the end of the month"
        git push
